### ISSUE TITLE
Update goodtables.yml to point to file/schema

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/pilot-pnnl#16]

**Comment by danfowler** [comment]
@samuelpayne @Tweety79rw @coldfire79 `goodtables.yml` now points to the file `metadata.tsv` and the schema that describes it `metadata-schema.json`: https://github.com/frictionlessdata/ADB-User-Study/commit/4b786a297d1ac3343fa00d7af918e5dbe7428c38
 

```
files:
  - source: metadata.tsv
    schema: metadata-schema.json
    skip_rows: ['#']
```
This is one way to pair a file with the schema that describes it.  The other is an actual `datapackage.json`.  We are doing this until we can fully support validating Data Packages on Good Tables.  @roll also added a `skip_rows` key so that Good Tables can skip over the metadata rows 2 & 3.
